name: Build the Containers

# Controls when the action will run.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      # so the repo will be crybapp-docker-portals
      repo-name-addition: crybapp-docker-
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [api, web, portals, portal, janus-docker]
    steps:
      - uses: actions/checkout@master
        with:
          repository: crybapp/${{ matrix.repo }}
          path: ./${{ matrix.repo }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.2.0
        env:
          tag: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.repo-name-addition}}${{ matrix.repo }}:latest
        with:
          push: push
          tags: ${{env.tag}}
          context: ./${{ matrix.repo }}
          file: ./${{ matrix.repo }}/Dockerfile
          # cache-from: type=registry,ref=${{env.tag}}
          # cache-to: type=inline
