name: Build the Containers

# Controls when the action will run.
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [api, web, portals, portal, janus-docker]
    steps:
      - 
        uses: actions/checkout@master
        with:
          repository: crybapp/${{ matrix.repo }}
          path: ./${{ matrix.repo }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: docker/build-push-action@v2.2.0
        with:
          push: push
          tags: user/${{ matrix.repo }}:latest
          context: ./${{ matrix.repo }}
          file: ./${{ matrix.repo }}/Dockerfile
          cache-from: type=registry,ref=user/${{ matrix.repo }}:latest
          cache-to: type=inline
